name: Build spd_dump

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make libusb-1.0-0-dev

      - name: Build
        run: make

      - name: Upload spd_dump
        uses: actions/upload-artifact@v4
        with:
          name: spd_dump
          path: spd_dump
